name: rosas
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  html: ^0.15.0
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  duration: ^3.0.11
  shared_preferences: ^2.0.13
  firebase_auth: ^3.3.12
  firebase_core: ^1.14.0
  cloud_firestore: ^3.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

    # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo/rosas-logo-512.png
    - assets/images/no-subscription-illustration.png
    - assets/images/auth-illustration.png

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
  fonts:
    - family: Archivo_SemiCondensed
      fonts:
        - asset: assets/fonts/Archivo_SemiCondensed/Archivo_SemiCondensed-Light.ttf
          weight: 300
        - asset: assets/fonts/Archivo_SemiCondensed/Archivo_SemiCondensed-Thin.ttf
          weight: 100
        - asset: assets/fonts/Archivo_SemiCondensed/Archivo_SemiCondensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/Archivo_SemiCondensed/Archivo_SemiCondensed-ExtraBoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Archivo_SemiCondensed/Archivo_SemiCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/Archivo_SemiCondensed/Archivo_SemiCondensed-ExtraBold.ttf
          weight: 700
        - asset: assets/fonts/Archivo_SemiCondensed/Archivo_SemiCondensed-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Archivo_SemiCondensed/Archivo_SemiCondensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Archivo_SemiCondensed/Archivo_SemiCondensed-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Archivo_SemiCondensed/Archivo_SemiCondensed-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Archivo_SemiCondensed/Archivo_SemiCondensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/Archivo_SemiCondensed/Archivo_SemiCondensed-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/Archivo_SemiCondensed/Archivo_SemiCondensed-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Archivo_SemiCondensed/Archivo_SemiCondensed-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/Archivo_SemiCondensed/Archivo_SemiCondensed-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Archivo_SemiCondensed/Archivo_SemiCondensed-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Archivo_SemiCondensed/Archivo_SemiCondensed-Black.ttf
          weight: 900
        - asset: assets/fonts/Archivo_SemiCondensed/Archivo_SemiCondensed-BlackItalic.ttf
          style: italic
          weight: 900
    - family: Archivo_Condensed
      fonts:
        - asset: assets/fonts/Archivo_Condensed/Archivo_Condensed-ExtraBold.ttf
          weight: 700
        - asset: assets/fonts/Archivo_Condensed/Archivo_Condensed-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Archivo_Condensed/Archivo_Condensed-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: assets/fonts/Archivo_Condensed/Archivo_Condensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Archivo_Condensed/Archivo_Condensed-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Archivo_Condensed/Archivo_Condensed-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/Archivo_Condensed/Archivo_Condensed-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Archivo_Condensed/Archivo_Condensed-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Archivo_Condensed/Archivo_Condensed-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Archivo_Condensed/Archivo_Condensed-Light.ttf
          weight: 300
        - asset: assets/fonts/Archivo_Condensed/Archivo_Condensed-Black.ttf
          weight: 900
        - asset: assets/fonts/Archivo_Condensed/Archivo_Condensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/Archivo_Condensed/Archivo_Condensed-Thin.ttf
          weight: 100
        - asset: assets/fonts/Archivo_Condensed/Archivo_Condensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/Archivo_Condensed/Archivo_Condensed-ExtraBoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Archivo_Condensed/Archivo_Condensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/Archivo_Condensed/Archivo_Condensed-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Archivo_Condensed/Archivo_Condensed-ExtraLightItalic.ttf
          style: italic
          weight: 200
    - family: Archivo_SemiExpanded
      fonts:
        - asset: assets/fonts/Archivo_SemiExpanded/Archivo_SemiExpanded-ExtraBoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Archivo_SemiExpanded/Archivo_SemiExpanded-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Archivo_SemiExpanded/Archivo_SemiExpanded-Medium.ttf
          weight: 500
        - asset: assets/fonts/Archivo_SemiExpanded/Archivo_SemiExpanded-Regular.ttf
          weight: 400
        - asset: assets/fonts/Archivo_SemiExpanded/Archivo_SemiExpanded-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Archivo_SemiExpanded/Archivo_SemiExpanded-Black.ttf
          weight: 900
        - asset: assets/fonts/Archivo_SemiExpanded/Archivo_SemiExpanded-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/Archivo_SemiExpanded/Archivo_SemiExpanded-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Archivo_SemiExpanded/Archivo_SemiExpanded-Light.ttf
          weight: 300
        - asset: assets/fonts/Archivo_SemiExpanded/Archivo_SemiExpanded-Thin.ttf
          weight: 100
        - asset: assets/fonts/Archivo_SemiExpanded/Archivo_SemiExpanded-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Archivo_SemiExpanded/Archivo_SemiExpanded-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: assets/fonts/Archivo_SemiExpanded/Archivo_SemiExpanded-Bold.ttf
          weight: 700
        - asset: assets/fonts/Archivo_SemiExpanded/Archivo_SemiExpanded-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/Archivo_SemiExpanded/Archivo_SemiExpanded-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Archivo_SemiExpanded/Archivo_SemiExpanded-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Archivo_SemiExpanded/Archivo_SemiExpanded-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Archivo_SemiExpanded/Archivo_SemiExpanded-ExtraBold.ttf
          weight: 700
    - family: Archivo_Expanded
      fonts:
        - asset: assets/fonts/Archivo_Expanded/Archivo_Expanded-Thin.ttf
          weight: 100
        - asset: assets/fonts/Archivo_Expanded/Archivo_Expanded-Light.ttf
          weight: 300
        - asset: assets/fonts/Archivo_Expanded/Archivo_Expanded-Regular.ttf
          weight: 400
        - asset: assets/fonts/Archivo_Expanded/Archivo_Expanded-Bold.ttf
          weight: 700
        - asset: assets/fonts/Archivo_Expanded/Archivo_Expanded-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: assets/fonts/Archivo_Expanded/Archivo_Expanded-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Archivo_Expanded/Archivo_Expanded-Medium.ttf
          weight: 500
        - asset: assets/fonts/Archivo_Expanded/Archivo_Expanded-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Archivo_Expanded/Archivo_Expanded-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Archivo_Expanded/Archivo_Expanded-ExtraBoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Archivo_Expanded/Archivo_Expanded-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Archivo_Expanded/Archivo_Expanded-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/Archivo_Expanded/Archivo_Expanded-ExtraBold.ttf
          weight: 700
        - asset: assets/fonts/Archivo_Expanded/Archivo_Expanded-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Archivo_Expanded/Archivo_Expanded-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/Archivo_Expanded/Archivo_Expanded-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Archivo_Expanded/Archivo_Expanded-Black.ttf
          weight: 900
        - asset: assets/fonts/Archivo_Expanded/Archivo_Expanded-BoldItalic.ttf
          style: italic
          weight: 700
    - family: Archivo
      fonts:
        - asset: assets/fonts/Archivo/Archivo-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: assets/fonts/Archivo/Archivo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Archivo/Archivo-Black.ttf
          weight: 900
        - asset: assets/fonts/Archivo/Archivo-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Archivo/Archivo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Archivo/Archivo-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Archivo/Archivo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Archivo/Archivo-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Archivo/Archivo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Archivo/Archivo-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/Archivo/Archivo-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Archivo/Archivo-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Archivo/Archivo-ExtraBoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Archivo/Archivo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Archivo/Archivo-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/Archivo/Archivo-ExtraBold.ttf
          weight: 700
        - asset: assets/fonts/Archivo/Archivo-Light.ttf
          weight: 300
        - asset: assets/fonts/Archivo/Archivo-Thin.ttf
          weight: 100
    - family: Archivo_ExtraCondensed
      fonts:
        - asset: assets/fonts/Archivo_ExtraCondensed/Archivo_ExtraCondensed-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Archivo_ExtraCondensed/Archivo_ExtraCondensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/Archivo_ExtraCondensed/Archivo_ExtraCondensed-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/Archivo_ExtraCondensed/Archivo_ExtraCondensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/Archivo_ExtraCondensed/Archivo_ExtraCondensed-Black.ttf
          weight: 900
        - asset: assets/fonts/Archivo_ExtraCondensed/Archivo_ExtraCondensed-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Archivo_ExtraCondensed/Archivo_ExtraCondensed-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Archivo_ExtraCondensed/Archivo_ExtraCondensed-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/Archivo_ExtraCondensed/Archivo_ExtraCondensed-Light.ttf
          weight: 300
        - asset: assets/fonts/Archivo_ExtraCondensed/Archivo_ExtraCondensed-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Archivo_ExtraCondensed/Archivo_ExtraCondensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Archivo_ExtraCondensed/Archivo_ExtraCondensed-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: assets/fonts/Archivo_ExtraCondensed/Archivo_ExtraCondensed-ExtraBoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Archivo_ExtraCondensed/Archivo_ExtraCondensed-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Archivo_ExtraCondensed/Archivo_ExtraCondensed-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Archivo_ExtraCondensed/Archivo_ExtraCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/Archivo_ExtraCondensed/Archivo_ExtraCondensed-ExtraBold.ttf
          weight: 700
        - asset: assets/fonts/Archivo_ExtraCondensed/Archivo_ExtraCondensed-Thin.ttf
          weight: 100
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
