// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9rCZC13qLGRKYBAO2dbWV3gMVqqXRmcA',
    appId: '1:256687657388:web:4b3da95a1e1f48d8b2aa09',
    messagingSenderId: '256687657388',
    projectId: 'rosas-ce1b4',
    authDomain: 'rosas-ce1b4.firebaseapp.com',
    storageBucket: 'rosas-ce1b4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCkimqEN_S1Zye6qOL-jMmheOZpgfGC8E',
    appId: '1:256687657388:android:8dfcc7eb3a36931bb2aa09',
    messagingSenderId: '256687657388',
    projectId: 'rosas-ce1b4',
    storageBucket: 'rosas-ce1b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8WI9hvRYV-oEKtnzMMjtgJSyyuhlYhkM',
    appId: '1:256687657388:ios:96f9834ce8606f93b2aa09',
    messagingSenderId: '256687657388',
    projectId: 'rosas-ce1b4',
    storageBucket: 'rosas-ce1b4.appspot.com',
    iosClientId: '256687657388-k0v2dhtnrs4hgenla3th8cogr38fug6v.apps.googleusercontent.com',
    iosBundleId: 'com.example.rosas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8WI9hvRYV-oEKtnzMMjtgJSyyuhlYhkM',
    appId: '1:256687657388:ios:96f9834ce8606f93b2aa09',
    messagingSenderId: '256687657388',
    projectId: 'rosas-ce1b4',
    storageBucket: 'rosas-ce1b4.appspot.com',
    iosClientId: '256687657388-k0v2dhtnrs4hgenla3th8cogr38fug6v.apps.googleusercontent.com',
    iosBundleId: 'com.example.rosas',
  );
}
