// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCkimqEN_S1Zye6qOL-jMmheOZpgfGC8E',
    appId: '1:256687657388:android:c159c4bb1fcb133ab2aa09',
    messagingSenderId: '256687657388',
    projectId: 'rosas-ce1b4',
    storageBucket: 'rosas-ce1b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8WI9hvRYV-oEKtnzMMjtgJSyyuhlYhkM',
    appId: '1:256687657388:ios:ce3624d046485b58b2aa09',
    messagingSenderId: '256687657388',
    projectId: 'rosas-ce1b4',
    storageBucket: 'rosas-ce1b4.appspot.com',
    iosClientId: '256687657388-aj9e2tepl7b88djnphqctroeo96mrk8n.apps.googleusercontent.com',
    iosBundleId: 'fr.arthurfontaine.rosas',
  );
}
